---
- hosts: all
  tasks:
         - name: Upload SDDM config
           copy:
                   src: files/sddm.conf
                   dest: /etc/sddm.conf

         - name: Remove lightdm
           apt:
                   name: lightdm
                   state: absent

         - name: Install SDDM
           apt:
                   name: sddm
                   state: present


