---
- hosts: all
  tasks:
         # LightDM doesn't find the session in /usr/local. 
         - name: Enable sessions from /usr/local in LightDM
           ini_file:
                   path: /etc/lightdm/lightdm.conf
                   section: LightDM
                   option: sessions-directory
                   value: /usr/share/lightdm/sessions:/usr/share/xsessions:/usr/share/wayland-sessions:/usr/local/share/xsessions:/usr/local/share/wayland-sessions

         - name: Enable autologin user
           ini_file:
                   path: /etc/lightdm/lightdm.conf
                   section: "Seat:*"
                   option: autologin-user
                   value: pi

         - name: Enable autologin session
           ini_file:
                   path: /etc/lightdm/lightdm.conf
                   section: "Seat:*"
                   option: autologin-session
                   value: sway


